name: BlinkZo
options:
  bundleIdPrefix: com.blinkZo
  deploymentTarget:
    iOS: 17.0
targets:
  BlinkZo:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
